services:

  backend:
    image: api-backend-flask
    build:
      context: .
    env_file: ".env"
    stop_signal: SIGINT
    environment:
      - FLASK_PORT=${FLASK_PORT:-5000}
      - FLASK_APP=${FLASK_APP:-app/app.py}
      - MONGODB_STRING_CONNECTION=${MONGODB_STRING_CONNECTION:-mongodb://mongo}
    volumes:
      - ./:/application
    depends_on:
      -  mongo
    ports:
      - 5000:5000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    